#!/bin/bash
#
# nombre              : clean-squid3-cache
# descripción         : Limpiar la caché de squid3
# autor               : Esteban M. Navas Martín
# fecha creación      : 19042017
# última modificación : 19042017
# uso                 : clean-squid3-cache
# instalación         : Guardar en  /usr/local/sbin/

#
# Copyright 2015, Esteban M. Navas Martín <algodelinux@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.
#

systemctl stop squid3.service && rm -Rf /var/spool/squid3/* && squid3 -z && systemctl start squid3.service
